import { Metadata } from "next"
import { getBlogPosts } from "@lib/data/site-content"
import LocalizedClientLink from "@modules/common/components/localized-client-link"

export const metadata: Metadata = { title: "Journal", description: "Stories, inspiration, and notes from our shop." }
export default async function BlogPage() {
  const posts = (await getBlogPosts()).sort((a, b) => new Date(b.published_at).getTime() - new Date(a.published_at).getTime())
  return <main className="bg-homestead-cream"><header className="border-b border-homestead-border px-6 py-16 text-center md:py-24"><p className="text-xs uppercase tracking-widest text-homestead-olive">Stories from the shop</p><h1 className="mt-3 font-heading text-5xl text-homestead-forest md:text-7xl">The Journal</h1><p className="mx-auto mt-5 max-w-xl text-homestead-muted">Ideas, inspiration, and a closer look at the things we love.</p></header><div className="content-container py-14 md:py-20">{posts.length ? <div className="grid gap-10 md:grid-cols-2 lg:grid-cols-3">{posts.map(post => <article key={post.id}><LocalizedClientLink href={`/blog/${post.slug}`} className="group block">{post.cover_image_url ? <div className="aspect-[4/3] overflow-hidden rounded-sm bg-homestead-linen"><img src={post.cover_image_url} alt={post.image_alt || ""} className="h-full w-full object-cover transition duration-500 group-hover:scale-105" /></div> : <div className="flex aspect-[4/3] items-center justify-center rounded-sm bg-homestead-linen font-heading text-6xl text-homestead-olive">✦</div>}<time className="mt-5 block text-xs uppercase tracking-widest text-homestead-muted">{new Date(post.published_at).toLocaleDateString(undefined, { year: "numeric", month: "long", day: "numeric" })}</time><h2 className="mt-2 font-heading text-3xl text-homestead-forest group-hover:underline">{post.title}</h2><p className="mt-3 leading-7 text-homestead-muted">{post.excerpt}</p><span className="mt-4 inline-flex text-sm font-semibold text-homestead-olive">Read story →</span></LocalizedClientLink></article>)}</div> : <p className="py-20 text-center font-heading text-3xl text-homestead-muted">New stories are coming soon.</p>}</div></main>
}
